### ISSUE TITLE
System.NullReferenceException while trying to retrieve InformationProtection Labels

### ISSUE THREAD

**Issue by FilipKaraba** [microsoftgraph/msgraph-beta-sdk-dotnet#100] opened 2020-04-23 09:39 UTC
While trying to retrieve Azure Information Protection Labels, I get the `System.NullReferenceException` exception. NuGet version `Microsoft.Graph.Beta.0.17.0-preview` . Tried several other versions, the results were the same.

Non-working code snippet :
```
var client = GetGraphServiceClient(...);
var labels = client.InformationProtection.Policy.Labels.Request().GetAsync().Result;
```

Doing a request to different accessor works fine, e.g. :
```
var users = client.Users.Request().Select("displayName,mailNickname,mail,id").GetAsync().Result;
```

Requesting via HttpClient() & GetAsync() works fine too :
```
HttpClient client2 = new HttpClient();
...
var response = client2.GetAsync("https://graph.microsoft.com/beta/informationProtection/policy/labels").Result;
```
returns the data expected :
```
{
  "@odata.context": "https://graph.microsoft.com/beta/$metadata#informationProtection/policy/labels",
  "value": [...]
}
``` 
[AB#7169](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7169)

**Comment by Paul-Konsolute** [comment] 2021-06-04 20:59
I am unable to retrieve any labels with the C# Graph Beta client (I get `System.NullReferenceException` as mentioned), nor am I able to get the labels via a HttpClient. (This Client is created via Dependency Injection in .net core an MVC API project)

The following code returns `400  : Bad Request`
```
                var httpMsg = new HttpRequestMessage(HttpMethod.Get, "https://graph.microsoft.com/beta/me/informationProtection/policy/labels");
                httpMsg.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
                var res = await this.client.SendAsync(httpMsg);
```

The token is valid and contains the following scopes

```
"scp": "Directory.Read.All email Group.Read.All Group.ReadWrite.All InformationProtectionPolicy.Read openid profile User.Read User.ReadBasic.All",
```

However, from the graph explorer it works just fine. What can I do to make this work in C#?

**Comment by Paul-Konsolute** [comment] 2021-06-04 21:49
Follow up to my previous answer : Set the `User-Agent` header to any value.
```
var msg = this.graphServiceClient.Me.InformationProtection.Policy.Labels
                                                      .Request().GetHttpRequestMessage();
msg.Headers.Add("Accept", "*/*");
msg.Headers.Add("User-Agent", "Graph Client repair job");
var labelsContent = await this.graphServiceClient.HttpProvider.SendAsync(msg);
```

This returns the expected result, however I am unable to see if `@odata.nextLink` works on this endpoint. Using `top`  will bring back only the specified records and no paging.

**Comment by andrueastman** [comment] 2021-06-07 06:46
@Paul-Konsolute Are you able to provide the version of the SDK you are using that reproduces the error?

**Comment by Paul-Konsolute** [comment] 2021-06-07 08:14
It was `0.36.0-preview` and `4.3.0-preview`

Another fix is to override `IAuthenticationProvider` and set the `UserAgent` in the `AuthenticateRequestAsync(HttpRequestMessage request)` It works using SDK as expected.

**Comment by andrueastman** [comment] 2021-06-07 08:51
Do you still need to set the headers with version `4.3.0-preview` when you use the following code?

```cs 
var informationProtectionPolicyLabelsCollectionPage = await graphServiceClient.Me.InformationProtection.Policy.Labels
                                                      .Request().GetAsync();
```

**Comment by Paul-Konsolute** [comment] 2021-06-08 08:02
Yes, i do, as I still get the `Object reference not set to an instance of an object` error.

**Comment by andrueastman** [comment] 2021-06-08 08:04
Could you capture a trace with Fiddler of the response and post the full exception stack trace to help us identify what might be causing the issue so that we may be fix it?

**Comment by Paul-Konsolute** [comment] 2021-06-08 08:12
GET https://graph.microsoft.com/beta/me/informationProtection/policy/labels HTTP/1.1
Host: graph.microsoft.com
SdkVersion: Graph-dotnet-2.0.0
FeatureFlag: 0000004F
Cache-Control: no-store, no-cache
Authorization: Bearer eyJ0eXAiOiJKV1QiL...
Accept-Encoding: gzip
Request-Id: |abdbe0fb-4e1ad0b745038ed6.6.


HTTP/1.1 400 Bad Request
Date: Tue, 08 Jun 2021 08:08:57 GMT
Content-Type: application/json
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 4b7cd9ed-6c62-4220-b349-2c73b15b96e1
client-request-id: 4b7cd9ed-6c62-4220-b349-2c73b15b96e1
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"003","RoleInstance":"LO2PEPF00000033"}}
Content-Length: 369

{"error":{"code":"invalidRequest","message":"The request is malformed or incorrect.","innerError":{"code":"missingArgument","message":"Value cannot be null. (Parameter 'User-Agent')","target":"User-Agent","exception":null,"date":"2021-06-08T08:08:58","request-id":"4b7cd9ed-6c62-4220-b349-2c73b15b96e1","client-request-id":"4b7cd9ed-6c62-4220-b349-2c73b15b96e1"}}}

**Comment by andrueastman** [comment] 2021-06-09 10:29
@Paul-Konsolute 
Thanks for this. The NullReferenceException  is caused by the `exception` property in the payload being set as null which is not what the SDK expects. We shall fix this so that the user may be able to view the API side error information.

With regards to having to set the user agent header, this is mentioned in the docs [here](https://docs.microsoft.com/en-us/graph/api/informationprotectionpolicy-list-labels?view=graph-rest-beta&tabs=http#request-headers). Though this is said to be optional, the way to do it using the SDK would be as follows.

```cs
var requestOptions = new List<Option>() 
{
    new HeaderOption("User-Agent","Test App")
};
var informationProtectionPolicyLabelsCollectionPage = await graphClient.Me.InformationProtection.Policy.Labels
                                            .Request(requestOptions).GetAsync();
```

We shall fix the null reference error and proceed to close the issue once this is done.

**Comment by Paul-Konsolute** [comment] 2021-06-09 12:01
Thanks for the update, and clarification on how I should be using the User-Agent for this call.

**Comment by andrueastman** [comment] 2021-06-18 07:50
Fix for the NullReference exception should now be available through https://www.nuget.org/packages/Microsoft.Graph.Beta/4.5.0-preview and fixed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/260

**Closed by andrueastman** 2021-06-18 07:50 UTC
Labels: Bug, promote
