### ISSUE TITLE
BETA: AdministrativeUnit Extension - Access Denied

### ISSUE THREAD

**Issue by ackermann81** [microsoftgraph/msgraph-beta-sdk-dotnet#465] opened 2022-06-04 20:45 UTC
Hi,
i try to enhance the administrativeUnits with an openextension object where i post additional data as xml. I´m using the same for Users and it works there, but for administrativeUnits i got a AccessDenied.

From the documentation it should work also Permissions should be fine as the application has AdministrativeUnit.ReadWrite.All and i can send update or create requests for administrativeUnits. Also Getting Extensions work fine.

My example is (C#):

var extension = new OpenTypeExtension
{
ExtensionName = "TEST",
AdditionalData = new Dictionary<string, object>()
{
{"XML", "Test"}
}
};

graphClient.AdministrativeUnits["11111111-2222-3333-4444-555555555555"].Extensions.Request().AddAsync(extension).Wait();

ERROR:
System.AggregateException: 'One or more errors occurred. (Code: AccessDenied
Message: Access Denied
Inner error:
AdditionalData:
date: 2022-06-04T20:38:24
request-id: 4bb5fcb7-72ae-4288-ac9a-e4e050f96ae3
client-request-id: 4bb5fcb7-72ae-4288-ac9a-e4e050f96ae3
ClientRequestId: 4bb5fcb7-72ae-4288-ac9a-e4e050f96ae3
)'

I already have seen the following issue that was closed https://github.com/microsoftgraph/microsoft-graph-docs/issues/3541.
But i can´t see a solution there.
Even with powershell its not possible to generate an OpenTypeExtension.

New-MgAdministrativeUnitExtension -AdministrativeUnitId 11111111-2222-3333-4444-555555555555 -Id TEST -AdditionalProperties @{ XML = "Test" }
ERROR:
New-MgAdministrativeUnitExtension : Access Denied
At line:1 char:1

New-MgAdministrativeUnitExtension -AdministrativeUnitId 8f2b8358-eb86 ...
  + CategoryInfo          : InvalidOperation: ({ Administrativ...raphExtension }:<>f__AnonymousType4`2) [New-MgAdmin
 istr..._CreateExpanded], RestException`1
  + FullyQualifiedErrorId : AccessDenied,Microsoft.Graph.PowerShell.Cmdlets.NewMgAdministrativeUnitExtension_CreateE
 xpanded

Thanks
Robert

**Comment by andrueastman** [comment] 2022-06-06 07:21
Hey @ackermann81,

Thanks for raising this. 

This looks to be an issue with the privileges used to make the request.

Any chance you can confirm that you have the permissions as outlined in the documentation at the link below? 

https://docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-1.0&tabs=http#permissions

Also, is the calling principal a Privileged Role Administrator a Global Administrator as outlined in the docs?

**Comment by andrueastman** [comment] 2022-06-08 14:38
Hey @ackermann81,

I can confirm that I can replicate the same behavior from my end. Since this seems to be an issue with API, I have raised a question at the link below so that we may be able to get clarification from the relevant API owners if this is a missing permission in the docs or an API bug.

https://docs.microsoft.com/en-us/answers/questions/881678/administrativeunit-extension-access-denied.html

For now, we will close this GitHub issue and re-open it in the event anything related to the client library is raised and follow up with the API issue from the link above.

**Closed by andrueastman** 2022-06-08 14:38 UTC
Labels: Question: API
