### ISSUE TITLE
Missing PageIterator

### ISSUE THREAD

**Issue by coolhome** [microsoftgraph/msgraph-beta-sdk-dotnet#159] opened 2020-09-24 14:49 UTC
Unable to use PageIterator from the non beta version. Unable to install side by side.
[AB#6166](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6166)

**Comment by andrueastman** [comment] 2021-04-22 09:23
Closing this as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/179 for now. We shall track the work there.
We will be moving this to the core library and will be available soon in the 4.x.x preview versions of the service libraries once the work is completed.

**Closed by andrueastman** 2021-04-22 09:23 UTC
Labels: enhancement, promote
