### ISSUE TITLE
Cannot access Win32LobApp from v5 Microsoft.Graph.Beta nuget package

### ISSUE THREAD

**Issue by garport** [microsoftgraph/msgraph-beta-sdk-dotnet#439] opened 2022-05-02 17:04 UTC
Cannot access Win32LobApp from v5 Microsoft.Graph.Beta nuget package

It does not seem to be exposed.

**Comment by garport** [comment] 2022-05-04 15:50
How can I create the Win32LobApp object in the new version?

**Comment by andrueastman** [comment] 2022-05-06 13:18
Hey @garport,

Thanks for raising this. 

It does indeed seem like the `Win32LobApp` model is missing from the model's folder in the V5 preview version of the SDK. 
I suspect that this may be caused by the fact that the model is not directly referenced from any of the OpenAPI paths but only its parent is referenced. 

For now, you may be able to work around this by something like this where you can use the base type to create the instance. 

```cs
        var win32LobApp = new MobileApp
        {
            DisplayName = "DisplayName",
            Description = "Description value",
            
            AdditionalData = new Dictionary<string, object>()
            {
                {"@odata.type","#microsoft.graph.win32LobApp"},//set the type
                {"minimumMemoryInMB",1} // add other win32LobApp properties here.
            }
        };
        
        await graphServiceClient.DeviceAppManagement.MobileApps.PostAsync(win32LobApp);
```

We're currently investigating the fix and will revert.

**Comment by garport** [comment] 2022-05-06 15:52
Thank you @andrueastman. There are also some other models that are missing involving requirements, detection and assignments. Should I list them here as well, or will they be fixed by that change as well?

**Comment by andrueastman** [comment] 2022-05-06 16:09
Hey @garport,

They should also be fixed by the change that will address https://github.com/microsoft/kiota/issues/1554 so that all the models that are also not directly referenced are included as well.

**Comment by marcoscheel** [comment] 2022-06-20 11:52
@andrueastman we are facing the same issue. We are buildings apps that upload Win32 LOB Apps to Microsoft Intune. We need for example the class for file encryption (FileEncryptionInfo). I can see the files are generated in this repo, but they are not part of the latest NUGET we are using in VS. With version 4.46.0-preview everything was fine and starting with 5.0.0-preview the needed classes are no longer available.

**Comment by andrueastman** [comment] 2022-06-21 14:03
With the latest update [5.7.0 preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.7.0-preview) we should be able take advantage of the Win32LobApp type.

@marcoscheel Any chance you can confirm in what scenario the `FileEncryptionInfo` type would be used? Looking at the openApi document [here](https://github.com/microsoftgraph/msgraph-metadata/tree/master/openapi/beta), the type does not seem to be referenced in any paths. This would help us identify if indeed there is a path missing in the openApi metadata.

**Comment by dansmitt** [comment] 2022-06-22 11:57
> With the latest update [5.7.0 preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.7.0-preview) we should be able take advantage of the Win32LobApp type.
> 
> @marcoscheel Any chance you can confirm in what scenario the `FileEncryptionInfo` type would be used? Looking at the openApi document [here](https://github.com/microsoftgraph/msgraph-metadata/tree/master/openapi/beta), the type does not seem to be referenced in any paths. This would help us identify if indeed there is a path missing in the openApi metadata.

@andrueastman You need the FileEncryptionInfo in combination with a ContentVersion at a commit. For example:

```c# 
await requestBuilder.ContentVersions[contentVersion.Id].Files[mobileAppContentFile.Id].Commit(FileEncryptionInfo).Request().PostAsync();
```

**Comment by garport** [comment] 2022-06-22 13:26
@andrueastman We use `FileEncryptionInfo` for our application imports as well. Should I send a full list of missing types? There were other missing types around group assignment and supersedence relationships as well (I haven't checked if they are in 5.7.0 yet)

**Comment by MarkusBux** [comment] 2022-06-27 12:25
Found other missing models as well. I.e. `Win32LobAppFileSystemDetection` or `win32LobAppFileSystemRule`. It is used within a `Win32LobApp` to created (detection) rules.

**Comment by garport** [comment] 2022-06-27 12:42
Here are the missing types I have found so far:
``
``
``
``

**Comment by garport** [comment] 2022-06-27 12:51
Here are the missing types I have found so far:
`Win32LobAppFileSystemDetectionType`
`Win32LobAppRegistryDetectionType`
`FileEncryptionInfo`
`MobileAppContentFileCommitRequestBuilder`
`MobileAppContentFilesCollectionRequestBuilder`
`ManagedMobileLobAppContentVersionsCollectionRequestBuilder`
`MobileAppContentFileRequestBuilder`
`Win32LobAppProductCodeDetection`
`Win32LobAppFileSystemDetection`
`Win32LobAppRegistryDetection`
`IMobileAppAssignmentsCollectionPage`
`TokenCredentialAuthProvider`
`MobileAppUpdateRelationshipsRequestBuilder`
`MobileAppAssignmentsCollectionRequestBuilder`
`MobileAppUpdateRelationshipsRequestBuilder`

Are some of those `RequestBuilder`s and `CollectionPage`s missing because of switching to Kiota? I included them because it seems some `RequestBuilder`s are still there.

**Comment by andrueastman** [comment] 2022-06-30 08:55
Thanks for trying out the new preview and the feedback.

With the fix made in the conversion library via https://github.com/microsoft/OpenAPI.NET.OData/pull/238 the missing types below should be now accessible in the latest update [5.8.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.8.0-preview) 

- Win32LobAppFileSystemDetectionType
- Win32LobAppRegistryDetectionType
- Win32LobAppProductCodeDetection
- Win32LobAppFileSystemDetection
- Win32LobAppRegistryDetection


> Are some of those RequestBuilders and CollectionPages missing because of switching to Kiota?

With regards to `FileEncryptionInfo` and its related request builders, we still need to resolve the openapi reference metadata to include paths referencing the derived types of `MobileApp` which we're tracking via https://github.com/microsoftgraph/msgraph-metadata/issues/179 as Kiota uses the openApi reference as opposed to csdl reference.

We'll keep this issue open as we resolve that on the metadata side so that the relevant requestbuilders are also included on upcoming generation updates.

**Comment by AnnaJac89** [comment] 2023-08-17 00:00
> > With the latest update [5.7.0 preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.7.0-preview) we should be able take advantage of the Win32LobApp type.
> > @marcoscheel Any chance you can confirm in what scenario the `FileEncryptionInfo` type would be used? Looking at the openApi document [here](https://github.com/microsoftgraph/msgraph-metadata/tree/master/openapi/beta), the type does not seem to be referenced in any paths. This would help us identify if indeed there is a path missing in the openApi metadata.
> 
> @andrueastman You need the FileEncryptionInfo in combination with a ContentVersion at a commit. For example:
> 
> ```cs
> await requestBuilder.ContentVersions[contentVersion.Id].Files[mobileAppContentFile.Id].Commit(FileEncryptionInfo).Request().PostAsync();
> ```

hi which requestbuilder has contentversions. i am not able to post a new content version using mobileAppsRequestbuilder. Kindly share how i can create a new contentversion for a new app

**Closed** 2023-10-06 12:01 UTC
Labels: Bug, OpenApi
