### ISSUE TITLE
Graph.Beta 4.0.1 IDeviceAppManagementMobileAppsCollectionPage NextPageRequest always null

### ISSUE THREAD

**Issue by schmid37** [microsoftgraph/msgraph-beta-sdk-dotnet#275] opened 2021-04-09 11:12 UTC
We facing an issue with the Graph.Beta 4.x so far. When we request an IDeviceAppManagementMobileAppsCollectionPage and it has more than one page, the NextRequestPage is always null. That is a problem if the wanted application is not on the first page.

Example code:

```cs
        public async Task<List<MobileApp>> GetApplicationByGridAsync(string grid)
        {
            List<MobileApp> mobileApps = new List<MobileApp>();

            var request = _graphClient.RetrieveGraphServiceClient().DeviceAppManagement.MobileApps.Request().Filter($"startsWith(displayName,'{grid}')");

            do
            {
                var apps = await request.GetAsync();
                mobileApps.AddRange(apps);
                request = apps.NextPageRequest;
            }
            while (request != null);

            return mobileApps;
        }
```

I did not verify if this happens to other collection pages, too. 
[AB#8913](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8913)

**Comment by DerGuru** [comment] 2021-04-09 11:21
Same issue here, with other ```ICollectionPages``` as well.
The link for the next page request is available in the additional data, but the NextPageRequest is null.

**Comment by schmid37** [comment] 2021-04-09 11:23
> Same issue here, with other `ICollectionPages` as well.
> The link for the next page request is available in the additional data, but the NextPageRequest is null.

Yes it is available in the additional data, but I think this should not be way to use it. Great that I'm not alone with this.

**Comment by DerGuru** [comment] 2021-04-09 11:37
The issue is not present in 0.42.0

**Comment by andrueastman** [comment] 2021-04-12 07:20
Thanks for raising this issue and for trying out the new preview. We shall investigate this and resolve this in the next update.

**Comment by andrueastman** [comment] 2021-04-22 09:16
This should be resolved in the latest release Microsoft.Graph.Beta 4.1.0-preview

**Closed by andrueastman** 2021-04-22 09:16 UTC
Labels: Bug
