### ISSUE TITLE
[Client bug]: The JSON value could not be converted to System.Nullable when querying assignments in 4.1.0-preview

### ISSUE THREAD

**Issue by Danialmz96** [microsoftgraph/msgraph-beta-sdk-dotnet#293] opened 2021-05-04 11:13 UTC
Querying assignments using a public graph client sometimes results in a parsing exception.
The full message is:
"The JSON value could not be converted to System.Nullable`1[Microsoft.Graph.EducationAssignmentStatus]. Path: $.status | LineNumber: 0 | BytePositionInLine: 616. Path: $.value | LineNumber: 0 | BytePositionInLine: 103580."

Note it is not of type Microsoft.Graph.ServiceException but a general exception which is understandable because it happens during parsing. It happens if there is an assignment with status Null.

Reproduce:
await publicGraphClient.Education.Classes[classId].Assignments
.Request()
.WithUsernamePassword(username, password)
.GetAsync(); 

SDK version: 4.1.0-preview

This is a code breaking bug, is there any workaround until it is fixed?
For example, is it possible to force the use of Newtonsoft.Json instead of System.Text.Json? 
[AB#9260](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9260)

**Comment by andrueastman** [comment] 2021-05-05 07:05
@Danialmz96 Thanks for reporting this issue and trying out the new preview. We shall investigate this and provide a fix. In the meantime, you can use version 0.44.0 preview which provides the same functionality but with Newtonsoft.Json.

**Comment by Danialmz96** [comment] 2021-05-07 07:56
[response.txt](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/files/6439963/response.txt)

@andrueastman 
The attached file contains the response string that results in the reported error.
As you said, a null status is not the cause and I have no idea what causes it.

**Comment by andrueastman** [comment] 2021-05-17 08:19
@Danialmz96 Thanks again for raising this issue.
It looks like the exception is caused by the api returning an Enum value not defined in the metadata. One of the items in the payload has a EducationAssignmentStatus value of "scheduled" which is not defined in the metadata as shown.
![image](https://user-images.githubusercontent.com/6464005/118454370-f6986e80-b700-11eb-8ba5-ee668c3df09c.png)

We will work on to handling such enum scenarios gracefully on the SDK side in an upcoming update and alert the api owners to update the metadata accordingly.

**Comment by andrueastman** [comment] 2021-05-24 07:38
The deserialization of the payload should now be fixed in version 4.3.0-preview. In the event an enum value does not exist in the model/metadata, you should be able to find the value in the AdditionalData bag like previous version of the sdk using NewtonSoft.

With regards to updating the metadata to add the "scheduled" value, this is tracked via https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/85.

Closing this for now.

**Closed by andrueastman** 2021-05-24 07:38 UTC
Labels: 1, Bug, under investigation
