### ISSUE TITLE
IncludeTargets missing from Fido2AuthenticationMethodConfiguration

### ISSUE THREAD

**Issue by delepster** [microsoftgraph/msgraph-beta-sdk-dotnet#788] opened 2024-01-09 18:47 UTC
Describe the bug
Property Fido2AuthenticationMethodConfiguration.IncludeTargets lost when updating from version 5.50.0-preview to 5.60.0-preview. Even though the odata property is present in the HTTP request

To Reproduce

update the package
rebuild the application which accesses `IncludeTargets
Expected behavior
The property should be accessible.

Desktop (please complete the following information):

OS: Windows
Browser: N/A
Version 5.60.0-preview

**Comment by andrueastman** [comment] 2024-01-15 09:37
Closing as duplicate of https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/776

**Closed by andrueastman** 2024-01-15 09:37 UTC
Labels: Bug: metadata, Status: Needs investigation
