### ISSUE TITLE
TeamworkTag ListMembers returns 100 rows but is not paged and top not allowed

### ISSUE THREAD

**Issue by ChrisGrove** [microsoftgraph/msgraph-beta-sdk-dotnet#526] opened 2022-08-31 09:50 UTC
Hi,
I am using the following code against version 4.55.0-preview to retrieve all members of a specific Tag. This  Tag has 121 members.

`var bob  = Global.GraphClient.Teams[TeamId].Tags[targetTagId].Members.Request().GetAsync().Result;`

Query return value:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/25799273/187649728-8638d438-6473-46b3-b655-b41e24bfb07b.png">

The result is only 100 rows long, which is the default page size, however the result does not contain a NextPageRequest and the adding of the Top clause is not supported and throws the following exception:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/25799273/187650222-b93d289f-5d89-439c-8eb1-fe7ff27e47e1.png">

Thanks
Chris

**Comment by raclettierer** [comment] 2022-10-03 13:09
I have the same problem, actually is this API useless if we can't get all members of a tag.

**Comment by andrueastman** [comment] 2022-11-29 08:26
Forwarded to the relevant team through this [incident](https://portal.microsofticm.com/imp/v3/incidents/details/351990734/home).

**Comment by JJarv04** [comment] 2023-02-03 06:39
Hi @andrueastman, is there a public facing area we can track this issue in? - As the issue isn't confined to the dotnet sdk, rather an issue with the graph api. 

It kinda makes this endpoint unreliable and unusable if the information it returns isn't complete. 
Thanks

**Comment by andrueastman** [comment] 2023-02-06 06:35
I hear you on this @JJarv04,

The respective API team has however confirmed that the fix has already been applied and is ready to be rolled out and within the next couple of weeks we should see that the API has the expected behavior.

**Comment by andrueastman** [comment] 2023-02-20 05:17
Closing this for now.

Team confirms that the fix has been rolled out.

**Closed by andrueastman** 2023-02-20 05:17 UTC
Labels: Service issue

**Comment by JJarv04** [comment] 2023-02-23 03:51
Had a look into this and it still appears to be broken. The resulting odata.nextlink url request now returns a Bad Request error, as shown below.
This request was made from Graph Explorer, also tried using v1.0/beta with no change.
```
{
    "error": {
        "code": "BadRequest",
        "message": "Value cannot be null. (Parameter 's')",
        "innerError": {
            "date": "2023-02-23T03:48:11",
            "request-id": "a8cb5b89-b90e-43de-bccf-c006edad8fd7",
            "client-request-id": "d3556ac6-efda-1bf0-b0bc-bb5f4c1bef18"
        }
    }
}
```
The link in question:
`    "@odata.nextLink": "https://graph.microsoft.com/beta/teams/cdf25aa2-f21c-4377-87b0-77f1ddacce2e/tags/MzQxZTI5NzMtNGE1Zi00YjFlLWI4OGMtMjhlMmEwN2Y5YmVkIyNjZGYyNWFhMi1mMjFjLTQzNzctODdiMC03N2YxZGRhY2NlMmUjI3RzT2FiTEJXTEQ=/members?$skiptoken=1.ktVizIvGAAAAi%2fIogapQcm9wZXJ0aWVzgbFDb250aW51YXRpb25Ub2tlbtlqK1JJRDp%2bN2FVd0FLWnlySGEtMGhJQQEA8D89PSNSVDoxI1RSQzoxMDAjSVNWOjIjSUVPOjY1NTUxI1FDRjo4I0ZQQzpBZ0ZMVVVzTUFMK1NBc0RmYnkvR01RQWlBRkVFQU9FaEFEOD0%3d",`

**Comment by andrueastman** [comment] 2023-02-23 05:19
Thanks for following up @JJarv04 

Any chance you can create a new issue with the added details so that we may follow up? 
Does this happen on all requests as well? Or when using default paging/with Top parameter?

**Comment by JJarv04** [comment] 2023-02-23 09:01
@andrueastman Thanks, have opened a new issue. 

> Does this happen on all requests as well? Or when using default paging/with Top parameter?

Will update it when I get a chance to look into again at work 👍 (My test tenant doesn't have enough Teams users in this case to trigger pagination)
