### ISSUE TITLE
Missing property includeTargets on fido2AuthenticationMethodConfiguration resource type from Beta version 5.54.0 and onwards

### ISSUE THREAD

**Issue by edwinvandriel** [microsoftgraph/msgraph-beta-sdk-dotnet#776] opened 2023-12-14 12:38 UTC
When upgrading the graph beta sdk from version 5.53.0 to the latest it breaks on the property includeTargets from the fido2AuthenticationMethodConfiguration type. The property disappears from version 5.54.0-preview and onwards.

The docs says it still should exist https://learn.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta

Hope this can be fixed soon, breaking change for us.

**Comment by andrueastman** [comment] 2023-12-14 13:53
Metadata available at https://graph.microsoft.com/beta/$metadata used to generate the SDK is also missing the the navigation property.
![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/6464005/98deab11-447c-444e-bb7b-0645b73bfc82)

We will need to confirm if this is a documentation issue or a mistake in the metadata. 

@edwinvandriel Any chance you can confirm that the relevant data is still returned/retrievable from the API?

**Comment by edwinvandriel** [comment] 2023-12-14 14:06
I can confirm it is still relevant. Think it's a mistake in the metadata

![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/11809810/569dcf37-c9f0-41a6-9479-a9c267aced08)

**Comment by edwinvandriel** [comment] 2024-01-05 10:46
@andrueastman any news on this one?

**Comment by andrueastman** [comment] 2024-01-15 09:41
The metadata was updated to have the `includeTargets` property to target a new derived type of `authenticationMethodTarget` that is not publicly and therefore stripped out of the final metadata. 

We're following up with the workload team on whether the removal of the property was intended here.

**Comment by edwinvandriel** [comment] 2024-01-30 11:59
Why should a removal be intended without a notice? It's a functionality that is also available in de v1 productions metadata. Could there be some more prio. It's now 6 weeks ago that i've been able to update the sdk :-(

**Comment by edwinvandriel** [comment] 2024-03-04 09:10
@andrueastman why isn't this solved yet?

**Comment by andrueastman** [comment] 2024-03-18 10:52
API team is working on fixing the metadata on this one and should be resolved once the updated metadata is deployed in the coming week.

**Comment by edwinvandriel** [comment] 2024-04-04 08:57
@andrueastman any update on this one? Still broken...

**Comment by tlrdstd** [comment] 2024-05-17 13:44
This has finally been fixed, as of https://github.com/microsoftgraph/msgraph-metadata/pull/623/commits/2329c74dc88c4bd0c0f0fc72bdc1faa95c7c40bf

It's supposed to be in the next NuGet release.

**Comment by andrueastman** [comment] 2024-05-24 06:12
Closing this one for now as the property was added via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/843 and available in the release at https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/releases/tag/v5.76.0-preview

**Closed by andrueastman** 2024-05-24 06:12 UTC
Labels: Bug: metadata
