### ISSUE TITLE
Getting two @odata.type properties in JSON when returning a MobileApp trough a custom API in 4.1.0

### ISSUE THREAD

**Issue by schmid37** [microsoftgraph/msgraph-beta-sdk-dotnet#290] opened 2021-04-27 13:09 UTC
Code: 
```cs
 public async Task<List<MobileApp>> GetApplicationByGridAsync(string grid)
        {
            List<MobileApp> mobileApps = new List<MobileApp>();

            DeviceAppManagementMobileAppsCollectionRequestBuilder rb = new DeviceAppManagementMobileAppsCollectionRequestBuilder($"https://graph.microsoft.com/beta/deviceAppManagement/mobileApps?$search=\"{grid}\"", _graphClient.RetrieveGraphServiceClient());

            var request = rb.Request();

            do
            {
                var apps = await request.GetAsync();
                mobileApps.AddRange(apps);
                request = apps.NextPageRequest;
            }
            while (request != null);

            return mobileApps;
        }
```

Return from custom API:

```json
...
        "@odata.type": "microsoft.graph.win32LobApp",
        "@odata.type": "#microsoft.graph.win32LobApp"
...
```

We can see from the incoming raw Graph call JSON contains only one  @odata.type (#microsoft.graph.win32LobApp). 
The representation of the Graph Data in the Graph SDK (Win32LobApp) has the ODataType propertie set to "microsoft.graph.win32LobApp". Also we can see that the AditionalData Array has one record also containing @odata.type": "#microsoft.graph.win32LobApp.

Reading our output of the custom API and casting to Win32LobApp results in an error: System.InvalidCastException: Unable to cast object of type 'Microsoft.Graph.MobileApp' to type 'Microsoft.Graph.Win32LobApp'.

 
[AB#9184](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9184)

**Comment by andrueastman** [comment] 2021-05-18 10:15
Hey @schmid37,
Any chance you could try this out with version 4.2.0-preview? I believe that [this update](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/249) in the core library should help. I am unable to replicate this on that version too.

**Comment by andrueastman** [comment] 2021-05-24 07:13
@schmid37 Closing this issue for now. Please feel free to reopen it if the latest version of the sdk(4.2.0-preview or 4.3.0-preview) does not resolve the issue.

**Closed by andrueastman** 2021-05-24 07:13 UTC
Labels: more-information-needed, under investigation

**Comment by schmid37** [comment] 2021-05-26 09:49
Hey @andrueastman it's still not working. Is it possible to get a demo meeting with you? We think to complexity is to high to describe it here in an issue. We got some examples in our productive application, where it's not working in serval ways with the 4.x
We think that this is an serialization issue with the new System.Text.Json way. With Newtonsoft.Json in the 0.x version everything works fine.

**Comment by andrueastman** [comment] 2021-05-26 09:57
Hey @schmid37,
I'm happy to organise a demo meeting. I'm not sure which meeting time/method works best for you but I can work with whatever works best for you.

**Comment by schmid37** [comment] 2021-05-26 10:00
@andrueastman may I contact you via mail?

**Comment by andrueastman** [comment] 2021-05-26 10:01
Sure. You can contact me at andrew.omondi@microsoft.com

**Comment by KBAlphaZA** [comment] 2021-07-08 19:23
Can we please get an update cause we are facing the same problem.

**Comment by andrueastman** [comment] 2021-07-09 07:00
@KBAlphaZA Are you also using a custom API? In the other case the issue was caused by using Newtonsoft and System.Text.Json together.

**Comment by KBAlphaZA** [comment] 2021-07-09 09:06
This might be unrelated but I get a key called @odata with the value "mirosoft.graph.driveitem", how do I go into a subfolder to go into a file?

**Comment by andrueastman** [comment] 2021-07-09 10:17
Any chance you could share a code sample of how you are trying to achieve your goal and what result you expect?
