### ISSUE TITLE
microsoft.graph.ediscovery.SourceType.site get's translated incorrectly

### ISSUE THREAD

**Issue by mahage-msft** [microsoftgraph/msgraph-beta-sdk-dotnet#267] opened 2021-03-30 19:49 UTC
When I try to use microsoft.graph.ediscovery.SourceType.site, site is translated as upper case (Site) - it needs to be all lower case (site).

Here's the fiddler trace (see bold) - 
POST https://graph.microsoft.com/beta/compliance/ediscovery/cases/102fa0bd-3d52-4056-9743-74e7b83d3457/custodians/46363131333630303541423141324436/userSources HTTP/1.1
Host: graph.microsoft.com
SdkVersion: Graph-dotnet-2.0.0
FeatureFlag: 0000004F
Cache-Control: no-store, no-cache
Accept-Encoding: gzip
Content-Type: application/json
Content-Length: 133

{"email":"jewell@ediscodemo.onmicrosoft.com",**"includedSources":"mailbox, Site"**,"@odata.type":"microsoft.graph.ediscovery.userSource"}
HTTP/1.1 400 Bad Request
Date: Tue, 30 Mar 2021 18:44:44 GMT
Content-Type: application/json
Cache-Control: no-cache
Transfer-Encoding: chunked
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: ea9ce00c-3876-4226-bef5-eacd0cc9161c
client-request-id: ea9ce00c-3876-4226-bef5-eacd0cc9161c
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US 2","Slice":"E","Ring":"1","ScaleUnit":"002","RoleInstance":"MWH0EPF00032D54"}}

This works in Graph Explorer if I change site to lower case.

 
[AB#8794](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8794)

**Comment by mahage-msft** [comment] 2021-03-30 20:16
Documentation for the SourceType is here - https://docs.microsoft.com/en-us/graph/api/resources/ediscovery-usersource?view=graph-rest-beta#sourcetype-values

**Comment by andrueastman** [comment] 2021-03-31 08:06
Thanks for raising this issue @mahage-msft.
The issue is caused by a bug that previously existed in System.Text.Json where the camelCasing naming policy was not consistently applied by flag enums. See here https://github.com/dotnet/runtime/issues/31622
We will resolve this soon with a dependency update.

**Comment by andrueastman** [comment] 2021-04-01 06:12
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/238

**Closed by andrueastman** 2021-04-01 06:12 UTC
Labels: Bug, under investigation
