### ISSUE TITLE
/chats/id/members returns a list of AadUserConversationMember but SDK deserializes to ConversationMember

### ISSUE THREAD

**Issue by akudhingra** [microsoftgraph/msgraph-beta-sdk-dotnet#190] opened 2020-11-10 17:47 UTC
The beta /chats/id/members endpoint returns a list of AadUserConversationMember  as shown below:

```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#chats('19%3A77ad52dsdsdsdsdsd89%40thread.skype')/members",
    "@odata.count": 1,
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "325f3c99-ff13-42b4-99c7-2sdsdsdsd3deb",
            "roles": [],
            "displayName": "Administrator",
            "userId": "325f3c99-ff13-42b4-99c7-2sdsdsdsd3deb",
        }
    ]
}
```

However, when using the SDK, it seems to deserialize this to a list of ConversationMember

```
IChatMembersCollectionPage chatMembers = await graphClient
                    .Chats[chatId]
                    .Members
                    .Request()
                    .GetAsync(cancellationToken.Token);

var allChatMembers = new List<ConversationMember>(chatMembers);
```

This means that to access UserId I need to convert each member to the derived type to get access to it's properties. I'm using the 0.32.0-preview version of the SDK and don't see any other classes deriving from ConversationMember. 

If we expect this endpoint to always return a list of the derived type, AadUserConversationMember, can the SDK be updated to match that so we can skip the manual conversion?

**Why do I need the UserId?**
Before November 10, 2020, the Id the UserId fields were set to the same value, the user's GUID. However, as of yesterday a small percentage of responses have Id set to a different value, leaving only the UserId field to get the user's GUID. Example:

```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#teams%28'670a0dfdf-28cb-43fd-9efc-2de2d60c23fe'%29/channels%28'19%3Ae6fbdfd8c9d23dfdf64%40thread.skype'%29/members/$entity@odata.type": "#microsoft.graph.aadUserConversationMember",
    "id": "NjcwYTBkODYtMjhjYi00M2ZkLTllZmMtMmRlMmQ2MGMyM2ZlIyNmODQwNGIwOS0zZmI4LTRjYmEtOTZjZC05YzMxZjBkNzViYjk=",
    "roles": [],
    "displayName": "Lee Adama",
    "userId": "f8404b09-3fb8-4cba-96cd-9cdfdf75bb9",
    "email": null
}
``` 
[AB#7146](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7146)

**Comment by Arik1337** [comment] 2020-11-11 15:58
I'm having a similar problem, the "id" is suddenly different than the "Guid" but sometimes It's fine. if you take the thing I get in the "id" and put it in https://www.base64decode.org/
after decoding it you get the string "{tenantId}##{chatId}##{userId}".
How should we get to the "UserId" field when getting members?

**Comment by akudhingra** [comment] 2020-11-11 18:52
@Arik1337 can you capture the response headers which should include the timestamp and the request-id and share it here? I believe that helps them investigate.

I can't seem to reproduce this at my end today.

**Comment by MIchaelMainer** [comment] 2020-11-12 21:34
The API is defined to return the base type. It may in the future return derived types other than `aadUserConversationMember`. This is by design. The SDK reflects this. The issue about the change in values for `id` and `userId`, this change is from the service.

**Comment by andrueastman** [comment] 2023-03-14 07:59
Closing this one for now. Property is accessible through the derived property

```cs
  var response = await graphServiceClient.Teams[$""].Members.Request().GetAsync();

  foreach(var conversationMember in response)
  {
      if (conversationMember is AadUserConversationMember aadUser)
      {
          var userID = aadUser.UserId;
      }
  }
```

**Closed by andrueastman** 2023-03-14 07:59 UTC
