### ISSUE TITLE
EmailAuthenticateMethod uses PATCH instead of PUT

### ISSUE THREAD

**Issue by s-summers** [microsoftgraph/msgraph-beta-sdk-dotnet#215] opened 2021-01-29 05:21 UTC
Attempting to update a user's email authentication method using the Microsoft.Graph.Beta v0.36.0 gives the following error
```
Code: UnknownError
Message: No HTTP resource was found that matches the request URI 'https://mface.windowsazure.com/odata/users('<user id>')/authentication/emailMethods('<email id>')'
```

When running the following
```cs
public async Task UpdateEmailAuthentication(string userId, string email)
{
    var userEmailMethods = await _client.Users[userId]
        .Authentication
        .EmailMethods
        .Request()
        .GetAsync();

    var userEmailMethod = userEmailMethods.First();
    var newEmailMethod = new EmailAuthenticationMethod
    {
        EmailAddress = email
    };

    await _client.Users[userId]
        .Authentication
        .EmailMethods[userEmailMethod.Id]
        .Request()
        .UpdateAsync(newEmailMethod);
}
```

Calling `.UpdateAsync` for EmailAuthenticateMethod sends the request as a PATCH rather than PUT as outlined in the docs

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/requests/EmailAuthenticationMethodRequest.cs#L151

The [beta reference docs](https://docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&tabs=csharp#http-request) suggest that a `PutAsync` method should exist but there isn't one available

Alternative solution to `.UpdateAsync` until then
```cs
var request = _client.Users[userId]
    .Authentication
    .EmailMethods[userEmailMethod.Id]
    .Request();

var msg = request.GetHttpRequestMessage();
msg.Method = System.Net.Http.HttpMethod.Put;
msg.Content = new System.Net.Http.StringContent(
    Newtonsoft.Json.JsonConvert.SerializeObject(newEmailMethod),
    System.Text.Encoding.UTF8,
    "application/json"
);

await request.Client.HttpProvider.SendAsync(msg);
``` 
[AB#7863](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7863)

**Comment by colinhqgit** [comment] 2021-02-02 17:21
This is also similar to a bogue with PhoneAuthenticationMethod.
I am not sure if I should have created a separate issue or not... (I apologize if I should have).

```
public async Task UpdateEmailAuthentication(string userId, string authenticationMethodId, string phoneNumber)
{
        var phoneAuthenticationMethod = new Beta.PhoneAuthenticationMethod
        {
            PhoneNumber = phoneNumber,
            PhoneType = AuthenticationPhoneType.Mobile
        };

        await _graphClient
            .Users[userId]
            .Authentication
            .PhoneMethods[authenticationMethodId]
            .Request()
            .UpdateAsync(phoneAuthenticationMethod);
}
```

This performs a PATCH instead of a PUT.

The [beta document](https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&tabs=csharp) also references to a PutSync.

**Comment by zengin** [comment] 2021-02-26 22:47
duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/844

**Closed by zengin** 2021-02-26 22:47 UTC
Labels: Bug
