### ISSUE TITLE
MS Graph & team

### ISSUE THREAD

**Issue by RayMa78** [microsoftgraph/msgraph-beta-sdk-dotnet#194] opened 2020-11-15 08:47 UTC
i see assign left my last issue and thats why i post again can you help me in here please ? 
Thanks for your response auctully its worked with one problem 
```
"attendees": [],
                "producers": [],
                "contributors": []
```
the problem is its showing only the organizer info even without the display name only id of him
! its not showing the but i faced another problem when i want to fetch with user id it gives the same error 
this is what code i use 
```
string body = string.Format("JoinWebUrl eq '{0}'", joinWeb);
var meetingTest = await graphServiceClient.Users[userId].OnlineMeetings
                .Request()
                .Filter(body)
                .GetAsync();
```
am i doing this wrong too ?

**Comment by RayMa78** [comment] 2020-11-17 07:40
any answer ?

**Comment by MIchaelMainer** [comment] 2020-11-19 18:56
Duplicate of https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/192

**Closed by MIchaelMainer** 2020-11-19 18:56 UTC
Labels: ToTriage, duplicate
